"""whatsapp inbound messages and bindings

Revision ID: 9924969df5ef
Revises: c3d5e7f9a1b4
Create Date: 2026-08-29 16:31:39.363890

Hand-trimmed from the autogenerated diff: this environment's autogenerate also picked up
~30 unrelated "added foreign key" / dropped-index entries across pre-existing tables (FK-naming
drift between the live DB and current models, unrelated to this feature) - those are
deliberately left out of this migration rather than applied blindly alongside the WhatsApp
tables. Only the WhatsApp-specific additions are included below.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9924969df5ef'
down_revision: Union[str, None] = 'c3d5e7f9a1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('whatsapp_inbound_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('sender_wa_number', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id')
    )
    op.create_index('idx_wa_inbound_status', 'whatsapp_inbound_messages', ['status'], unique=False)
    op.create_index('idx_wa_inbound_user_id', 'whatsapp_inbound_messages', ['user_id'], unique=False)
    op.create_index('idx_wa_inbound_wa_message_id', 'whatsapp_inbound_messages', ['wa_message_id'], unique=False)

    op.create_table('whatsapp_bindings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wa_phone_number', sa.String(length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_method', sa.String(length=30), nullable=True),
    sa.Column('pending_code_hash', sa.String(length=255), nullable=True),
    sa.Column('pending_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_session_id', sa.UUID(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_session_id'], ['ai_chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wa_binding_number_active', 'whatsapp_bindings', ['wa_phone_number', 'superseded_at'], unique=False)
    op.create_index('idx_wa_binding_user_id', 'whatsapp_bindings', ['user_id'], unique=False)

    # server_default backfills existing ai_chat_sessions rows so NOT NULL can be enforced
    # without failing on rows that predate this column (matches the model's Python-side default).
    op.add_column('ai_chat_sessions', sa.Column('channel', sa.String(length=20), nullable=False, server_default='web'))


def downgrade() -> None:
    op.drop_column('ai_chat_sessions', 'channel')

    op.drop_index('idx_wa_binding_user_id', table_name='whatsapp_bindings')
    op.drop_index('idx_wa_binding_number_active', table_name='whatsapp_bindings')
    op.drop_table('whatsapp_bindings')

    op.drop_index('idx_wa_inbound_wa_message_id', table_name='whatsapp_inbound_messages')
    op.drop_index('idx_wa_inbound_user_id', table_name='whatsapp_inbound_messages')
    op.drop_index('idx_wa_inbound_status', table_name='whatsapp_inbound_messages')
    op.drop_table('whatsapp_inbound_messages')
