"""initial_schema

Revision ID: ffc32bb2a843
Revises: 
Create Date: 2026-06-26 19:13:25.592549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc32bb2a843'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create required extensions and schemas before any tables
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_record_ids', sa.Text(), nullable=True),
    sa.Column('disclaimer_included', sa.Boolean(), nullable=False),
    sa.Column('disclaimer_text', sa.Text(), nullable=True),
    sa.Column('disclaimer_language', sa.String(length=10), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_messages_flagged', 'ai_chat_messages', ['flagged_for_review'], unique=False)
    op.create_index('idx_ai_messages_session_id', 'ai_chat_messages', ['session_id'], unique=False)
    op.create_index('idx_ai_messages_session_timeline', 'ai_chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_ai_messages_user_id', 'ai_chat_messages', ['user_id'], unique=False)
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('disclaimer_shown_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_sessions_user_active', 'ai_chat_sessions', ['user_id', 'status'], unique=False)
    op.create_index('idx_ai_sessions_user_id', 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_entity_type', sa.String(length=30), nullable=True),
    sa.Column('linked_entity_id', sa.UUID(), nullable=True),
    sa.Column('push_delivered', sa.Boolean(), nullable=False),
    sa.Column('push_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_active_unread', 'alerts', ['user_id', 'is_deleted', 'is_read'], unique=False)
    op.create_index('idx_alerts_priority', 'alerts', ['priority'], unique=False)
    op.create_index('idx_alerts_user_id', 'alerts', ['user_id'], unique=False)
    op.create_index('idx_alerts_user_timeline', 'alerts', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_alerts_user_unread', 'alerts', ['user_id', 'is_read'], unique=False)
    op.create_table('allergy_intolerances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('fhir_resource_id', sa.String(length=255), nullable=True),
    sa.Column('substance_name', sa.String(length=255), nullable=False),
    sa.Column('snomed_code', sa.String(length=50), nullable=True),
    sa.Column('snomed_display', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('criticality', sa.String(length=30), nullable=True),
    sa.Column('clinical_status', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('reaction_description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_correction_flag', sa.Boolean(), nullable=False),
    sa.Column('ai_correction_note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_allergies_snomed', 'allergy_intolerances', ['snomed_code'], unique=False)
    op.create_index('idx_allergies_source_record', 'allergy_intolerances', ['source_record_id'], unique=False)
    op.create_index('idx_allergies_user_id', 'allergy_intolerances', ['user_id'], unique=False)
    op.create_index('idx_allergies_user_status', 'allergy_intolerances', ['user_id', 'clinical_status'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('biometric_lock_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('drug_interaction_alerts', sa.Boolean(), nullable=False),
    sa.Column('lab_result_alerts', sa.Boolean(), nullable=False),
    sa.Column('vital_threshold_alerts', sa.Boolean(), nullable=False),
    sa.Column('analytics_opt_in', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role_snapshot', sa.String(length=50), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('actor_device_type', sa.String(length=20), nullable=True),
    sa.Column('actor_user_agent', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_owner_user_id', sa.UUID(), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('outcome_status', sa.String(length=20), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('access_purpose', sa.String(length=30), nullable=True),
    sa.Column('break_glass_reason', sa.Text(), nullable=True),
    sa.Column('additional_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hash_chain_value', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False, schema='audit')
    op.create_index('idx_audit_actor_timeline', 'audit_logs', ['actor_user_id', 'created_at'], unique=False, schema='audit')
    op.create_index('idx_audit_actor_user', 'audit_logs', ['actor_user_id'], unique=False, schema='audit')
    op.create_index('idx_audit_created_at', 'audit_logs', ['created_at'], unique=False, schema='audit')
    op.create_index('idx_audit_owner_timeline', 'audit_logs', ['resource_owner_user_id', 'created_at'], unique=False, schema='audit')
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False, schema='audit')
    op.create_index('idx_audit_resource_owner', 'audit_logs', ['resource_owner_user_id'], unique=False, schema='audit')
    op.create_table('conditions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('fhir_resource_id', sa.String(length=255), nullable=True),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('icd11_code', sa.String(length=30), nullable=True),
    sa.Column('icd11_display', sa.String(length=255), nullable=True),
    sa.Column('snomed_code', sa.String(length=50), nullable=True),
    sa.Column('snomed_display', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('clinical_status', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('abatement_date', sa.Date(), nullable=True),
    sa.Column('attending_physician', sa.String(length=255), nullable=True),
    sa.Column('care_plan_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_correction_flag', sa.Boolean(), nullable=False),
    sa.Column('ai_correction_note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conditions_icd11', 'conditions', ['icd11_code'], unique=False)
    op.create_index('idx_conditions_snomed', 'conditions', ['snomed_code'], unique=False)
    op.create_index('idx_conditions_source_record', 'conditions', ['source_record_id'], unique=False)
    op.create_index('idx_conditions_user_id', 'conditions', ['user_id'], unique=False)
    op.create_index('idx_conditions_user_status', 'conditions', ['user_id', 'clinical_status'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=60), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consent_type', 'consent_records', ['consent_type'], unique=False)
    op.create_index('idx_consent_user_id', 'consent_records', ['user_id'], unique=False)
    op.create_index('idx_consent_user_type', 'consent_records', ['user_id', 'consent_type'], unique=False)
    op.create_table('data_deletion_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('requested_via', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_export_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('export_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('download_url_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sharing_consents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grantee_name', sa.String(length=255), nullable=True),
    sa.Column('grantee_type', sa.String(length=20), nullable=False),
    sa.Column('grantee_institution', sa.String(length=255), nullable=True),
    sa.Column('access_scope', sa.String(length=30), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_data_sharing_user_id', 'data_sharing_consents', ['user_id'], unique=False)
    op.create_index('idx_data_sharing_user_status', 'data_sharing_consents', ['user_id', 'status'], unique=False)
    op.create_table('doctor_share_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('qr_token_hash', sa.String(length=255), nullable=False),
    sa.Column('share_scope', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=50), nullable=True),
    sa.Column('scanned_by_name', sa.String(length=255), nullable=True),
    sa.Column('scanned_by_institution', sa.String(length=255), nullable=True),
    sa.Column('scanned_ip', sa.String(length=45), nullable=True),
    sa.Column('scanned_user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token_hash')
    )
    op.create_index('idx_doctor_share_expires_at', 'doctor_share_sessions', ['expires_at'], unique=False)
    op.create_index('idx_doctor_share_status', 'doctor_share_sessions', ['status'], unique=False)
    op.create_index('idx_doctor_share_token_hash', 'doctor_share_sessions', ['qr_token_hash'], unique=False)
    op.create_index('idx_doctor_share_user_id', 'doctor_share_sessions', ['user_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emergency_contacts_primary', 'emergency_contacts', ['user_id', 'is_primary'], unique=False)
    op.create_index('idx_emergency_contacts_user_id', 'emergency_contacts', ['user_id'], unique=False)
    op.create_table('emergency_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lock_screen_widget_enabled', sa.Boolean(), nullable=False),
    sa.Column('show_blood_group', sa.Boolean(), nullable=False),
    sa.Column('show_allergies', sa.Boolean(), nullable=False),
    sa.Column('show_emergency_contacts', sa.Boolean(), nullable=False),
    sa.Column('show_chronic_conditions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('fhir_resource_id', sa.String(length=255), nullable=True),
    sa.Column('encounter_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('practitioner_name', sa.String(length=255), nullable=True),
    sa.Column('practitioner_specialty', sa.String(length=100), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_correction_flag', sa.Boolean(), nullable=False),
    sa.Column('ai_correction_note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_encounters_source_record', 'encounters', ['source_record_id'], unique=False)
    op.create_index('idx_encounters_start_dt', 'encounters', ['start_datetime'], unique=False)
    op.create_index('idx_encounters_user_id', 'encounters', ['user_id'], unique=False)
    op.create_index('idx_encounters_user_type', 'encounters', ['user_id', 'encounter_type'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('fhir_patient_id', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('photo_key', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fhir_patient_id')
    )
    op.create_index('idx_family_fhir_patient_id', 'family_members', ['fhir_patient_id'], unique=False)
    op.create_index('idx_family_owner_active', 'family_members', ['owner_user_id', 'is_deleted'], unique=False)
    op.create_index('idx_family_owner_user_id', 'family_members', ['owner_user_id'], unique=False)
    op.create_table('fhir_resource_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('internal_resource_type', sa.String(length=50), nullable=False),
    sa.Column('internal_resource_id', sa.UUID(), nullable=False),
    sa.Column('fhir_resource_type', sa.String(length=50), nullable=False),
    sa.Column('fhir_resource_id', sa.String(length=255), nullable=False),
    sa.Column('fhir_server_url', sa.String(length=500), nullable=True),
    sa.Column('fhir_version', sa.String(length=10), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_system_id', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('sync_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fhir_mapping_fhir_resource', 'fhir_resource_mappings', ['fhir_resource_type', 'fhir_resource_id'], unique=False)
    op.create_index('idx_fhir_mapping_internal_unique', 'fhir_resource_mappings', ['internal_resource_type', 'internal_resource_id'], unique=True)
    op.create_index('idx_fhir_mapping_source_system', 'fhir_resource_mappings', ['source_system'], unique=False)
    op.create_index('idx_fhir_mapping_sync_status', 'fhir_resource_mappings', ['sync_status'], unique=False)
    op.create_table('integration_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_integration_tokens_active_expiry', 'integration_tokens', ['is_active', 'token_expires_at'], unique=False)
    op.create_index('idx_integration_tokens_user_id', 'integration_tokens', ['user_id'], unique=False)
    op.create_index('idx_integration_tokens_user_provider', 'integration_tokens', ['user_id', 'provider'], unique=True)
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('fhir_resource_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('patient_name_on_doc', sa.String(length=255), nullable=True),
    sa.Column('laboratory_name', sa.String(length=255), nullable=True),
    sa.Column('referring_doctor', sa.String(length=255), nullable=True),
    sa.Column('issuing_organization', sa.String(length=255), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_summary_model_version', sa.String(length=50), nullable=True),
    sa.Column('is_dicom', sa.Boolean(), nullable=False),
    sa.Column('dicom_study_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('dicom_series_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('dicom_sop_class_uid', sa.String(length=255), nullable=True),
    sa.Column('deletion_type', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medical_records_date', 'medical_records', ['record_date'], unique=False)
    op.create_index('idx_medical_records_family_member_id', 'medical_records', ['family_member_id'], unique=False)
    op.create_index('idx_medical_records_folder_id', 'medical_records', ['folder_id'], unique=False)
    op.create_index('idx_medical_records_processing_status', 'medical_records', ['processing_status'], unique=False)
    op.create_index('idx_medical_records_user_active', 'medical_records', ['user_id', 'is_deleted'], unique=False)
    op.create_index('idx_medical_records_user_id', 'medical_records', ['user_id'], unique=False)
    op.create_index('idx_medical_records_user_type', 'medical_records', ['user_id', 'record_type'], unique=False)
    op.create_table('medication_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.Column('fhir_resource_id', sa.String(length=255), nullable=True),
    sa.Column('medication_name_raw', sa.String(length=255), nullable=False),
    sa.Column('dosage_instruction', sa.Text(), nullable=True),
    sa.Column('dose_quantity', sa.String(length=100), nullable=True),
    sa.Column('dose_frequency', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('prescribing_doctor', sa.String(length=255), nullable=True),
    sa.Column('prescribed_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_correction_flag', sa.Boolean(), nullable=False),
    sa.Column('ai_correction_note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_med_requests_medication_id', 'medication_requests', ['medication_id'], unique=False)
    op.create_index('idx_med_requests_source_record', 'medication_requests', ['source_record_id'], unique=False)
    op.create_index('idx_med_requests_user_id', 'medication_requests', ['user_id'], unique=False)
    op.create_index('idx_med_requests_user_status', 'medication_requests', ['user_id', 'status'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('atc_code', sa.String(length=7), nullable=True),
    sa.Column('atc_display', sa.String(length=255), nullable=True),
    sa.Column('snomed_code', sa.String(length=50), nullable=True),
    sa.Column('snomed_display', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medications_atc_code', 'medications', ['atc_code'], unique=False)
    op.create_index('idx_medications_generic_name', 'medications', ['generic_name'], unique=False)
    op.create_index('idx_medications_name', 'medications', ['name'], unique=False)
    op.create_table('observation_components',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('loinc_code', sa.String(length=20), nullable=True),
    sa.Column('loinc_display', sa.String(length=255), nullable=True),
    sa.Column('component_name', sa.String(length=255), nullable=False),
    sa.Column('value_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('value_unit', sa.String(length=50), nullable=True),
    sa.Column('value_string', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_obs_components_observation_id', 'observation_components', ['observation_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('fhir_resource_id', sa.String(length=255), nullable=True),
    sa.Column('loinc_code', sa.String(length=20), nullable=True),
    sa.Column('loinc_display', sa.String(length=255), nullable=True),
    sa.Column('observation_category', sa.String(length=30), nullable=False),
    sa.Column('observation_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('value_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('value_unit', sa.String(length=50), nullable=True),
    sa.Column('value_string', sa.String(length=255), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('reference_range_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('reference_range_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('interpretation', sa.String(length=20), nullable=True),
    sa.Column('effective_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_site', sa.String(length=100), nullable=True),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_correction_flag', sa.Boolean(), nullable=False),
    sa.Column('ai_correction_note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_observations_effective_dt', 'observations', ['effective_datetime'], unique=False)
    op.create_index('idx_observations_loinc', 'observations', ['loinc_code'], unique=False)
    op.create_index('idx_observations_source_record', 'observations', ['source_record_id'], unique=False)
    op.create_index('idx_observations_trend_query', 'observations', ['user_id', 'loinc_code', 'effective_datetime'], unique=False)
    op.create_index('idx_observations_user_category', 'observations', ['user_id', 'observation_category'], unique=False)
    op.create_index('idx_observations_user_id', 'observations', ['user_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename')
    )
    op.create_table('push_notification_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_push_tokens_user_id', 'push_notification_tokens', ['user_id'], unique=False)
    op.create_index('idx_push_tokens_user_platform', 'push_notification_tokens', ['user_id', 'platform'], unique=False)
    op.create_table('record_folders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_record_folders_user_active', 'record_folders', ['user_id', 'is_deleted'], unique=False)
    op.create_index('idx_record_folders_user_id', 'record_folders', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_permissions_unique', 'role_permissions', ['role_id', 'permission_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('security_incidents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_user_id', sa.UUID(), nullable=True),
    sa.Column('affected_user_count', sa.Integer(), nullable=True),
    sa.Column('affected_data_types', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_users_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_regulator_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remediation_notes', sa.Text(), nullable=True),
    sa.Column('post_mortem_url', sa.String(length=500), nullable=True),
    sa.Column('reported_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_affected_user', 'security_incidents', ['affected_user_id'], unique=False)
    op.create_index('idx_incidents_discovered_at', 'security_incidents', ['discovered_at'], unique=False)
    op.create_index('idx_incidents_severity', 'security_incidents', ['severity'], unique=False)
    op.create_index('idx_incidents_status', 'security_incidents', ['status'], unique=False)
    op.create_table('user_otp_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_expires_at', 'user_otp_requests', ['expires_at'], unique=False)
    op.create_index('idx_otp_recipient_purpose', 'user_otp_requests', ['recipient', 'purpose'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id_display', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('profile_photo_key', sa.String(length=255), nullable=True),
    sa.Column('profile_completion_pct', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id_display'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_profiles_patient_display_id', 'user_profiles', ['patient_id_display'], unique=False)
    op.create_index('idx_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_roles_expiry', 'user_roles', ['is_active', 'valid_until'], unique=False)
    op.create_index('idx_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_index('idx_user_roles_user_role', 'user_roles', ['user_id', 'role_id'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash'),
    sa.UniqueConstraint('session_token_hash')
    )
    op.create_index('idx_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_token_hash', 'user_sessions', ['session_token_hash'], unique=False)
    op.create_index('idx_sessions_user_active', 'user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('oauth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('data_region', sa.String(length=10), nullable=False),
    sa.Column('fhir_patient_id', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.String(length=50), nullable=True),
    sa.Column('scheduled_purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fhir_patient_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('idx_users_data_region', 'users', ['data_region'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_fhir_patient_id', 'users', ['fhir_patient_id'], unique=False)
    op.create_index('idx_users_is_deleted', 'users', ['is_deleted'], unique=False)
    op.create_index('idx_users_phone', 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_index('idx_users_is_deleted', table_name='users')
    op.drop_index('idx_users_fhir_patient_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_data_region', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_sessions_user_active', table_name='user_sessions')
    op.drop_index('idx_sessions_token_hash', table_name='user_sessions')
    op.drop_index('idx_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('idx_user_roles_user_role', table_name='user_roles')
    op.drop_index('idx_user_roles_user_id', table_name='user_roles')
    op.drop_index('idx_user_roles_expiry', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_user_profiles_user_id', table_name='user_profiles')
    op.drop_index('idx_user_profiles_patient_display_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('idx_otp_recipient_purpose', table_name='user_otp_requests')
    op.drop_index('idx_otp_expires_at', table_name='user_otp_requests')
    op.drop_table('user_otp_requests')
    op.drop_index('idx_incidents_status', table_name='security_incidents')
    op.drop_index('idx_incidents_severity', table_name='security_incidents')
    op.drop_index('idx_incidents_discovered_at', table_name='security_incidents')
    op.drop_index('idx_incidents_affected_user', table_name='security_incidents')
    op.drop_table('security_incidents')
    op.drop_table('roles')
    op.drop_index('idx_role_permissions_unique', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('idx_record_folders_user_id', table_name='record_folders')
    op.drop_index('idx_record_folders_user_active', table_name='record_folders')
    op.drop_table('record_folders')
    op.drop_index('idx_push_tokens_user_platform', table_name='push_notification_tokens')
    op.drop_index('idx_push_tokens_user_id', table_name='push_notification_tokens')
    op.drop_table('push_notification_tokens')
    op.drop_table('permissions')
    op.drop_index('idx_observations_user_id', table_name='observations')
    op.drop_index('idx_observations_user_category', table_name='observations')
    op.drop_index('idx_observations_trend_query', table_name='observations')
    op.drop_index('idx_observations_source_record', table_name='observations')
    op.drop_index('idx_observations_loinc', table_name='observations')
    op.drop_index('idx_observations_effective_dt', table_name='observations')
    op.drop_table('observations')
    op.drop_index('idx_obs_components_observation_id', table_name='observation_components')
    op.drop_table('observation_components')
    op.drop_index('idx_medications_name', table_name='medications')
    op.drop_index('idx_medications_generic_name', table_name='medications')
    op.drop_index('idx_medications_atc_code', table_name='medications')
    op.drop_table('medications')
    op.drop_index('idx_med_requests_user_status', table_name='medication_requests')
    op.drop_index('idx_med_requests_user_id', table_name='medication_requests')
    op.drop_index('idx_med_requests_source_record', table_name='medication_requests')
    op.drop_index('idx_med_requests_medication_id', table_name='medication_requests')
    op.drop_table('medication_requests')
    op.drop_index('idx_medical_records_user_type', table_name='medical_records')
    op.drop_index('idx_medical_records_user_id', table_name='medical_records')
    op.drop_index('idx_medical_records_user_active', table_name='medical_records')
    op.drop_index('idx_medical_records_processing_status', table_name='medical_records')
    op.drop_index('idx_medical_records_folder_id', table_name='medical_records')
    op.drop_index('idx_medical_records_family_member_id', table_name='medical_records')
    op.drop_index('idx_medical_records_date', table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index('idx_integration_tokens_user_provider', table_name='integration_tokens')
    op.drop_index('idx_integration_tokens_user_id', table_name='integration_tokens')
    op.drop_index('idx_integration_tokens_active_expiry', table_name='integration_tokens')
    op.drop_table('integration_tokens')
    op.drop_index('idx_fhir_mapping_sync_status', table_name='fhir_resource_mappings')
    op.drop_index('idx_fhir_mapping_source_system', table_name='fhir_resource_mappings')
    op.drop_index('idx_fhir_mapping_internal_unique', table_name='fhir_resource_mappings')
    op.drop_index('idx_fhir_mapping_fhir_resource', table_name='fhir_resource_mappings')
    op.drop_table('fhir_resource_mappings')
    op.drop_index('idx_family_owner_user_id', table_name='family_members')
    op.drop_index('idx_family_owner_active', table_name='family_members')
    op.drop_index('idx_family_fhir_patient_id', table_name='family_members')
    op.drop_table('family_members')
    op.drop_index('idx_encounters_user_type', table_name='encounters')
    op.drop_index('idx_encounters_user_id', table_name='encounters')
    op.drop_index('idx_encounters_start_dt', table_name='encounters')
    op.drop_index('idx_encounters_source_record', table_name='encounters')
    op.drop_table('encounters')
    op.drop_table('emergency_settings')
    op.drop_index('idx_emergency_contacts_user_id', table_name='emergency_contacts')
    op.drop_index('idx_emergency_contacts_primary', table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index('idx_doctor_share_user_id', table_name='doctor_share_sessions')
    op.drop_index('idx_doctor_share_token_hash', table_name='doctor_share_sessions')
    op.drop_index('idx_doctor_share_status', table_name='doctor_share_sessions')
    op.drop_index('idx_doctor_share_expires_at', table_name='doctor_share_sessions')
    op.drop_table('doctor_share_sessions')
    op.drop_index('idx_data_sharing_user_status', table_name='data_sharing_consents')
    op.drop_index('idx_data_sharing_user_id', table_name='data_sharing_consents')
    op.drop_table('data_sharing_consents')
    op.drop_table('data_export_requests')
    op.drop_table('data_deletion_requests')
    op.drop_index('idx_consent_user_type', table_name='consent_records')
    op.drop_index('idx_consent_user_id', table_name='consent_records')
    op.drop_index('idx_consent_type', table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index('idx_conditions_user_status', table_name='conditions')
    op.drop_index('idx_conditions_user_id', table_name='conditions')
    op.drop_index('idx_conditions_source_record', table_name='conditions')
    op.drop_index('idx_conditions_snomed', table_name='conditions')
    op.drop_index('idx_conditions_icd11', table_name='conditions')
    op.drop_table('conditions')
    op.drop_index('idx_audit_resource_owner', table_name='audit_logs', schema='audit')
    op.drop_index('idx_audit_resource', table_name='audit_logs', schema='audit')
    op.drop_index('idx_audit_owner_timeline', table_name='audit_logs', schema='audit')
    op.drop_index('idx_audit_created_at', table_name='audit_logs', schema='audit')
    op.drop_index('idx_audit_actor_user', table_name='audit_logs', schema='audit')
    op.drop_index('idx_audit_actor_timeline', table_name='audit_logs', schema='audit')
    op.drop_index('idx_audit_action', table_name='audit_logs', schema='audit')
    op.drop_table('audit_logs', schema='audit')
    op.drop_table('app_settings')
    op.drop_index('idx_allergies_user_status', table_name='allergy_intolerances')
    op.drop_index('idx_allergies_user_id', table_name='allergy_intolerances')
    op.drop_index('idx_allergies_source_record', table_name='allergy_intolerances')
    op.drop_index('idx_allergies_snomed', table_name='allergy_intolerances')
    op.drop_table('allergy_intolerances')
    op.drop_index('idx_alerts_user_unread', table_name='alerts')
    op.drop_index('idx_alerts_user_timeline', table_name='alerts')
    op.drop_index('idx_alerts_user_id', table_name='alerts')
    op.drop_index('idx_alerts_priority', table_name='alerts')
    op.drop_index('idx_alerts_active_unread', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_ai_sessions_user_id', table_name='ai_chat_sessions')
    op.drop_index('idx_ai_sessions_user_active', table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    op.drop_index('idx_ai_messages_user_id', table_name='ai_chat_messages')
    op.drop_index('idx_ai_messages_session_timeline', table_name='ai_chat_messages')
    op.drop_index('idx_ai_messages_session_id', table_name='ai_chat_messages')
    op.drop_index('idx_ai_messages_flagged', table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    # ### end Alembic commands ###
